In [1]:
# implementing neural network
# This will contain 3 inputs, four hidden neurons, and two output neurons

import numpy as np
import pandas as pd

In [2]:
# defining inputs and outputs

x1 = np.array(range(1,11))
x2 = np.array(range(11,21))
x3 = np.array(range(21,31))

y1 = np.array(range(101,111))
y2 = np.array(range(111,121))

In [7]:
# defining weights

hidden_weights = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
]
)
print(hidden_weights)

output_weights = np.array([
    [1.3, 1.4, 1.5, 1.6],
    [1.7, 1.8, 1.9, 2.0]
])
print(output_weights)

[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]
[[1.3 1.4 1.5 1.6]
 [1.7 1.8 1.9 2. ]]


In [10]:
# making a single vector for inputs
input_vector = np.array([x1[0], x2[0], x3[0]])
print(input_vector)

# making a single vector for outputs
output_vector = np.array([y1[0], y2[0]])
print(output_vector)

[ 1 11 21]
[101 111]


In [23]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def derivative_sigmoid(x):
    return x*(1-x)

## Feed Forward Pass

In [16]:
layer1 = np.dot(input_vector, hidden_weights) + np.array([1,1,1,1])
layer1 = sigmoid(layer1)
print(layer1)

layer2 = np.dot(layer1, output_weights.T) + np.array([1,1])
layer2 = sigmoid(layer2)
print(layer2)

[1. 1. 1. 1.]
[0.99888746 0.99977518]


## Combined Implementation

In [27]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Defining inputs and outputs
x1 = np.array(range(1, 11))
x2 = np.array(range(11, 21))
x3 = np.array(range(21, 31))

y1 = np.array(range(101, 111))
y2 = np.array(range(111, 121))

# Initializing weights and biases
np.random.seed(42)
w1 = np.random.rand(4, 3)  # Weights of the first hidden layer
b1 = np.random.rand(4, 1)  # Biases of the first hidden layer
w2 = np.random.rand(4, 4)  # Weights of the second hidden layer
b2 = np.random.rand(4, 1)  # Biases of the second hidden layer
w3 = np.random.rand(2, 4)  # Weights of the output layer
b3 = np.random.rand(2, 1)  # Biases of the output layer

# Forward propagation
z1 = np.dot(w1, np.array([x1, x2, x3])) + b1
a1 = sigmoid(z1)
z2 = np.dot(w2, a1) + b2
a2 = sigmoid(z2)
z3 = np.dot(w3, a2) + b3
a3 = sigmoid(z3)

# Calculating the output error
delta3 = a3 - np.array([y1, y2])
delta2 = np.dot(w3.T, delta3) * sigmoid_derivative(z2)
delta1 = np.dot(w2.T, delta2) * sigmoid_derivative(z1)

# Backward propagation (updating weights and biases)
learning_rate = 0.1
w3 -= learning_rate * np.dot(delta3, a2.T)
b3 -= learning_rate * np.sum(delta3, axis=1, keepdims=True)
w2 -= learning_rate * np.dot(delta2, a1.T)
b2 -= learning_rate * np.sum(delta2, axis=1, keepdims=True)
w1 -= learning_rate * np.dot(delta1, np.array([x1, x2, x3]).T)
b1 -= learning_rate * np.sum(delta1, axis=1, keepdims=True)


### For singular vector of Inputs

In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Defining inputs and outputs
x = np.array([1, 11, 21])  # Single input vector
y = np.array([101, 111])  # Single output vector

# Initializing weights and biases
np.random.seed(42)
w1 = np.random.rand(4, 3)  # Weights of the first hidden layer
b1 = np.random.rand(4, 1)  # Biases of the first hidden layer
w2 = np.random.rand(4, 4)  # Weights of the second hidden layer
b2 = np.random.rand(4, 1)  # Biases of the second hidden layer
w3 = np.random.rand(2, 4)  # Weights of the output layer
b3 = np.random.rand(2, 1)  # Biases of the output layer

# Forward propagation
z1 = np.dot(w1, x.reshape(-1, 1)) + b1
a1 = sigmoid(z1)
z2 = np.dot(w2, a1) + b2
a2 = sigmoid(z2)
z3 = np.dot(w3, a2) + b3
a3 = sigmoid(z3)

# Calculating the output error
delta3 = a3 - y.reshape(-1, 1)
delta2 = np.dot(w3.T, delta3) * sigmoid_derivative(z2)
delta1 = np.dot(w2.T, delta2) * sigmoid_derivative(z1)

# Backward propagation (updating weights and biases)
learning_rate = 0.1
w3 -= learning_rate * np.dot(delta3, a2.T)
b3 -= learning_rate * np.sum(delta3, axis=1, keepdims=True)
w2 -= learning_rate * np.dot(delta2, a1.T)
b2 -= learning_rate * np.sum(delta2, axis=1, keepdims=True)
w1 -= learning_rate * np.dot(delta1, x.reshape(1, -1))
b1 -= learning_rate * np.sum(delta1, axis=1, keepdims=True)
